//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizonBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingSeats
    {
        public int ID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> SeatID { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Seats Seats { get; set; }
    }
}
