//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizonBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public Bookings()
        {
            this.BookingSeats = new HashSet<BookingSeats>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public Nullable<int> NumberOfTickets { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<BookingSeats> BookingSeats { get; set; }
    }
}
