//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizonBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public Flights()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Seats = new HashSet<Seats>();
        }
    
        public int FlightID { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string FlightTime { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual ICollection<Seats> Seats { get; set; }
    }
}
