//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizonBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        public Seats()
        {
            this.BookingSeats = new HashSet<BookingSeats>();
        }
    
        public int SeatID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public string SeatNumber { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<int> BookingID { get; set; }
    
        public virtual ICollection<BookingSeats> BookingSeats { get; set; }
        public virtual Flights Flights { get; set; }
    }
}
